name: binary_search_uzimizniki
description: A package for performing binary search on sorted lists in Dart.
version: 1.0.0
repository: https://github.com/parvisss/binary-search-.git
homepage: https://github.com/parvisss/binary-search-.git

environment:
  sdk: ^3.3.2

dependencies:
  # Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

